---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-st
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: demo-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1  # Pod数
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: kanatakita/demo-graceful-shutdown:latest
        imagePullPolicy: Always
        ports:
        - name: port
          containerPort: 8080  # Pod の待ち受けるPort
        volumeMounts:
        readinessProbe:
          httpGet:
            path: /health  # ヘルスチェックパスを指定
            port: port
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health  # ヘルスチェックパスを指定
            port: port
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
